INSERT INTO USER(USER_NAME,PASSWORD,NAME,SURNAME,ROLE) VALUES('normal','normal','a','a','NORMAL')
INSERT INTO USER(USER_NAME,PASSWORD,NAME,SURNAME,ROLE) VALUES('admin','admin','a','a','ADMIN')
INSERT INTO normal_user_allergies VALUES (1,2)